apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-appointment
  template:
    metadata:
      labels:
        app: gke-appointment
    spec:
      containers:
        - name: appointment
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          


---
apiVersion: v1
kind: Service
metadata:
  name: appointment-srv
spec:
  selector:
    app: gke-deployment
  ports:
    - name: appointment
      protocol: TCP
      port: 3000
      targetPort: 3000
