apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
        - ./k8s/
build: 
  local:
    push: false
  artifacts:
    - image: adhiman24/appointment
      context: appointment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - index.js
            dest: .
